In [2]:
import numpy as np
# 生成形状为（samples, sequence_length, features）的随机数组
sequence_length = 5
features = 3

# 生成随机数据作为示例
data = np.random.randint(0, 10,(sequence_length, features))
data = data.astype(np.float32)
print(data)
# 计算每个特征维度的最小值和最大值
min_vals = np.min(data, axis=0)  # 每个特征维度的最小值
max_vals = np.max(data, axis=0)  # 每个特征维度的最大值
min_vals = np.expand_dims(min_vals, axis=0)
max_vals = np.expand_dims(max_vals, axis=0)
print(min_vals.shape)
print(max_vals.shape)
# 对每个特征维度进行 min-max 归一化处理
normalized_data = (data - min_vals) / (max_vals - min_vals)
print(normalized_data)

[[4. 2. 4.]
 [1. 8. 5.]
 [4. 6. 5.]
 [7. 2. 8.]
 [9. 3. 3.]]
(1, 3)
(1, 3)
[[0.375      0.         0.2       ]
 [0.         1.         0.4       ]
 [0.375      0.6666667  0.4       ]
 [0.75       0.         1.        ]
 [1.         0.16666667 0.        ]]
